#!/bin/bash

# $Id: 907-gpm 3540 2012-02-01 23:29:37Z thomasp $

set -e
cd $PKGDIR

./configure --prefix=/usr --sysconfdir=/etc
make
if ! [ -z $PKG_DEST ]; then
	mkdir -pv $PKG_DEST/{lib,usr/{share/{man,doc,info},lib}}
	ln -sv share/{man,doc,info} $PKG_DEST/usr
	case $(uname -m) in
	 x86_64) ln -sv lib $PKG_DEST/lib64 && ln -sv lib $PKG_DEST/usr/lib64 ;;
	esac
fi
make DESTDIR=$PKG_DEST install
ln -v -s libgpm.so.2.1.0 $PKG_DEST/usr/lib/libgpm.so
mkdir -pv $PKG_DEST/etc
install -v -m644 conf/gpm-root.conf $PKG_DEST/etc
install -v -m755 -d $PKG_DEST/usr/share/doc/gpm-1.20.6
chmod   -v   755    doc/{changes,support}
chmod   -v   644    doc/{changes/*,support/*,FAQ,HACK_GPM,README*}
cp      -v -R       doc/{FAQ,HACK_GPM,README*,changes,support} \
                    $PKG_DEST/usr/share/doc/gpm-1.20.6
if ! [ -z $PKG_DEST ]; then 
	rm -fv $PKG_DEST/{,usr/}lib64 
	rm -fv $PKG_DEST/usr/{man,doc,info}
        for dir in $PKG_DEST/usr/share/{doc,info,man}; do
          [[ -z $(ls $dir) ]] && rmdir -v $dir
        done
        for dir in $PKG_DEST/usr/{lib,share}; do
          [[ -z $(ls $dir) ]] && rmdir -v $dir
        done
        for dir in $PKG_DEST/{lib,usr}; do
          [[ -z $(ls $dir) ]] && rmdir -v $dir
        done
	packInstall
fi
rm -rf $PKG_DEST

exit
